baseURL = "https://mattmcelhannon.github.io/mattmcelhannon.com/"
languageCode = "en-us"
publishDir = "docs"
title = "Matt McElhannon"
theme = "ezhil"
paginate = 5

copyright = "© 2020 Matt McElhannon"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

summaryLength = 20

[params]
	subtitle = "Nothing happens to me."
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "dark" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/mattmcelhannon"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/mattmcelhannon/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mattmcelhannon"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/mattmcelhannon/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mattmcelhannon"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
